name: Send FCM Notification

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allows manual run from GitHub UI

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests google-auth

      - name: Decode and write service account file
        run: |
          printf "%s" "${{ secrets.FCM_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > service_account.json

      - name: Run notification script
        run: python send_notification.py
